--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/KadTheHunter/Core
build-by-default: true
branches:
- master
projects:
  Core:
    path: ""
    libs:
    - src: jojoe77777/FormAPI/libFormAPI
      version: ^1.3
...
