name: Core
main: Core\Core
api: 3.15.0
version: 5.10.0
load: POSTWORLD
author: KadTheHunter
commands:
  gms:
    description: Changes your gamemode to Creative
    permission: core.gms.use
  gmc:
    description: Changes your gamemode to Survival
    permission: core.gmc.use
  gma:
    description: Changes your gamemode to Adventure
    permission: core.gma.use
  gmspc:
    description: Changes your gamemode to Spectator
    permission: core.gmspc.use
  day:
    description: Changes the time to Day in the world your in
    permission: core.day.use
  night:
    description: Changes the time to Night in the world you're in
    permission: core.night.use
  nv:
    description: Gives you Night Vision
  clearinv:
    description: Clears you're Inventory
    aliases: ["invclear"]
  tpworld:
    description: Teleports you to another world
    usage: /tpworld <freebuild|city|treegarden>
    permission: core.tpworld.use
  itemid:
    description: Tells you the ID:Meta of the item you're holding.
    aliases: ["ii"]
  changesign:
    description: Allows you to change sign text
    usage: /cs <Line '#'> <Text>
    permission: core.changesign.use
    aliases: ["cs"]
  info:
    description: Shows the servers Information
  portals:
    description: Main Portals commmand
    usage: /portal pos1|pos2|create|delete|set|list
    permission: core.portals.admin
  lock:
    description: Locks Doors, Trapdoors, and Chests
    usage: /lock <keyName>
    permission: core.lock.use
  unlock:
    description: Unlocks Doors, Trapdoors, and Chests
    permission: core.unlock.use
  makekey:
    description: Makes a key for a Locked Door, Trapdoor or Chest
    usage: /makekey <keyName>
    permission: core.makekey.use
  lockedinfo:
    description: Gets information on a Locked Door, Trapdoor or Chest
    permission: core.lockedinfo.use
  hub:
    description: Teleports you to the Hub
    aliases: ["lobby","spawn"]
  rules:
    description: Shows the servers Rules

permissions:
  core.gmc.use:
    description: GMC Command
    default: OP
  core.gms.use:
    description: GMS Command
    default: OP
  core.gma.use:
    description: GMA Command
    default: OP
  core.gmspc.use:
    description: GMSPC Command
    default: OP
  core.day.use:
    description: DAY Command
    default: OP
  core.night.use:
    description: NIGHT Command
    default: OP
  core.tpworld.use:
    description: TPWORLD Command
    default: OP
  core.changesign.use:
    description: CHANGESIGN Command
    default: OP
  core.portals.admin:
    description: PORTALS Commands
    default: OP
  core.lock.use:
    description: LOCK Command
    default: OP
  core.unlock.use:
    description: UNLOCK Command
    default: OP
  core.makekey.use:
    description: MAKEKEY Command
    default: OP
  core.lockedinfo.use:
    description: LOCKEDINFO Command
    default: OP
  core.locks.break:
    description: Allows breaking any Locked Doors
    default: OP
  core.locks.bypass:
    description: Allows bypassing any Locked Doors
    default: OP
  core.banitem.bypass:
    description: Allows bypassing BanItem
    default: OP
