name: Core
main: Core\Core
api: 3.15.0
version: 5.5.3
mcpe-protocol: [407, 408, 419, 422]
load: POSTWORLD
author: KadTheHunter
commands:
  gms:
    description: Changes your gamemode to Creative
    permission: core.gms.use
  gmc:
    description: Changes your gamemode to Survival
    permission: core.gmc.use
  gma:
    description: Changes your gamemode to Adventure
    permission: core.gma.use
  gmspc:
    description: Changes your gamemode to Spectator
    permission: core.gmspc.use
  day:
    description: Changes the time to Day in the world your in
    permission: core.day.use
  night:
    description: Changes the time to Night in the world you're in
    permission: core.night.use
  nv:
    description: Gives you Night Vision
  clearinv:
    description: Clears you're Inventory
    aliases: ["invclear"]
  tpworld:
    description: Teleports you to another world
    permission: core.tpworld.use
  itemid:
    description: Tells you the ID:Meta of the item you're holding.
    aliases: ["ii"]
  lightning:
    description: Summons lightning to you
    permission: core.lightning.use
    aliases: ["ln", "lightn"]
  changesign:
    description: Allows you to change sign text
    usage: /cs <Line '#'> <Text>
    permission: core.changesign.use
    aliases: ["cs"]
  playtime:
    description: Shows how much you've played on the server
    aliases: ["pt", "playt"]
  togglemessages:
    description: Allows toggling the rotating messages on/off
  hub:
    description: Teleports you to the Hub
    aliases: ["lobby","spawn"]
  rules:
    description: Shows the servers Rules
  info:
    description: Shows the servers Information

permissions:
  core.gmc.use:
    description: GMC Command
    default: OP
  core.gms.use:
    description: GMS Command
    default: OP
  core.gma.use:
    description: GMA Command
    default: OP
  core.gmspc.use:
    description: GMSPC Command
    default: OP
  core.day.use:
    description: DAY Command
    default: OP
  core.night.use:
    description: NIGHT Command
    default: OP
  core.lightning.use:
    description: Allows usage of all Lightning related things.
    default: OP
  core.tpworld.use:
    description: TPWORLD Command
    default: OP
  core.changesign.use:
    description: CHANGESIGN Command
    default: OP